### ISSUE TITLE
comments need reload

### ISSUE THREAD

**Issue by joe-gz** [ga-wdi-exercises/project3#122]
Hi, when I add a comment, it immediately shows up on my browser.  However, I need to reload the page before I can actually delete that comment.  Given that this is a single page app, that seems odd, is there a trick to getting the page to either reload automatically, or auto-save something when i add it?

Thanks!

**Comment by RobertAKARobin** [comment]
That's because the browser doesn't know the comment has been deleted -- it's not aware of any changes to the comments in the database until it reloads the data from comments. You can fake it by using front-end Javascript to remove the comment's element in the DOM.

**Comment by joe-gz** [comment]
Hey Robin! Sorry, I actually have it working when I delete the comments.  The issue is when I add a comment. It appears on the page when I click submit, but, if say I wanted to immediately delete it, then it won't let me until i refresh the page.. Does that make sense? Is it a similar issue?

**Comment by RobertAKARobin** [comment]
Ah, I see. Yep, similar issue. After you submit a comment, the one that shows up on the page is probably a "fake" comment, in the same way that you can fake deleting a comment just by removing the element from the page.

In order to actually delete a comment you need to know its ID, and I imagine that you don't have it set up yet that when you create a comment you also save its ID somewhere. So that's the challenge: after POSTing a comment, how can you save its database ID so that you can later delete it?

Keep in mind: I'd say this isn't essential to your MVP. You can assume that your users are going to follow the rules and not try to delete a comment after creating it. So if you have other things to work on, go work on those. (But if not, feel free to keep on trucking with this.)

**Comment by joe-gz** [comment]
Ah ok perfect, that makes sense. Thanks for the quick response! I can close this now
