### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/project3#123]
I only receive the above error when I intentionally try to break our project. By spam clicking the button the sends our API calls. However, in my research I'm finding that error generally occurs under more strenuous activity so I think something is going wrong in our code but I can't pin point where. We do have a number of recursive functions but I can't figure out one that might be hitting that upper limit.

**Comment by RobertAKARobin** [comment]
Since this is an edge case, I wouldn't let it keep you from working on other things that need doing.

That said -- yeah, memory leaks are tough to pin town. The first thing I'd try is just console logging everywhere to see if there's one particular console log that keeps repeating. Failing that you'll need to get craftier. I'd recommend just Googling "javascript memory leak".

**Comment by ghost** [comment]
Fair enough!

Thanks
