### ISSUE TITLE
Rspec terminal commands -  w/ or w/o `bundle exec`?

### ISSUE THREAD

**Issue by ckib16** [ga-wdi-exercises/project3#16]
## Question

I'm seeing lots of Rspec tutorials expecting me to run rspec with `bundle exec rspec`. But Rspec seems to run just fine when I run `rspec` (without `bundle exec`).
- [ ] I'm confused as to why so many tutorials say to add `bundle exec` to most commands when we haven't had to do that in this course. 
- [ ] Did we add a specific alias to our BASH profile in the InstallFest (like the article below mentions) to avoid having to type `bundle exec`?
## Research / Tried So Far...

http://garbled.benhamill.com/2013/09/03/never-type-bundle-exec-again/

**Comment by RobertAKARobin** [comment]
`bundle exec rspec` tells RSpec to run using dependencies as they are explicitly defined in your Gemfile -- that is, which version of each dependency it should use. Without the `bundle exec`, RSpec will just use the default versions of those dependencies.

Usually the default version works just fine, which is why we rarely used `bundle exec` in-class.

**Comment by ckib16** [comment]
Ah. Ok, gotcha.

Is that the same reason we don't need to use `bin/spec` as it says in some tutorials?

**Comment by RobertAKARobin** [comment]
Probably! Haven't seen that before.
