### ISSUE TITLE
User auth signup - Users not persisting 

### ISSUE THREAD

**Issue by kaustly** [ga-wdi-exercises/project3#19]
Users aren't saving after signing up. Not redirecting to the home page per our controller.
Users.js:
<img width="1440" alt="screen shot 2015-12-05 at 11 51 42 am" src="https://cloud.githubusercontent.com/assets/13460389/11608969/aa46ff96-9b46-11e5-8f44-476492a393ae.png">
Schema.js
<img width="1440" alt="screen shot 2015-12-05 at 11 51 47 am" src="https://cloud.githubusercontent.com/assets/13460389/11608970/ae5f0164-9b46-11e5-98f3-50a045189f8e.png">
app.js
<img width="1440" alt="screen shot 2015-12-05 at 11 52 19 am" src="https://cloud.githubusercontent.com/assets/13460389/11608971/b04e1f28-9b46-11e5-90f9-92c7141e025a.png">

**Comment by amaseda** [comment]
@kaustly

Can you include your controller code as well?

Not sure if this will fix the problem, but I notice on Line 10 of `models/user.js` that you're referencing your password like so: `this.local.password`. This assumes your User schema looks something like this...

``` js
var UserSchema = new Schema({
  local: {
    email: String,
    password: String
    // + anything else you want to include in your local User model.
  }
})
```

So that's one thing you'll want to fix in your User model.

The `local` here refers to users that sign up for your application the old-fashioned way (i.e., just a username and password). If you chose to authenticate users via 3rd party applications (e.g., Facebook), you would then add another object to your User schema. It might look something like this...

``` js
var UserSchema = new Schema({
  local: {
    email: String,
    password: String
    // + anything else you want to include in your User model.
  },
  facebook: {
    id: String,
    token: String,
    email: String,
    name: String
  }
})
```

Of course, there is more code that goes into setting that up.

**Comment by lewis2ba** [comment]
<img width="1280" alt="screen shot 2015-12-05 at 5 21 01 pm" src="https://cloud.githubusercontent.com/assets/13842987/11610563/a72ae81c-9b74-11e5-9ccf-5cbc2d88db57.png">

Hey Adrian, thanks and sorry for the delayed response. Here is our users controller. After submitting the post request we dont get a redirect to the "/" route. We are also getting this error/warning(?) 

```
express-session deprecated undefined resave option; provide resave option app.js:26:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:26:9
```

Nodemon still runs and localhost is accessible  but I dont know if this is affecting it or not.

**Comment by lewis2ba** [comment]
I made the changes to the schema like you suggested but it still seems to be having the same problem.

**Comment by lewis2ba** [comment]
Also, I noticed that our model differs from the example models. The example uses:

```
User.methods.validPassword = function(password) {
     return bcrypt.compareSync(password, this.local.password);
  };
```

and we dont have the .methods  on our User model. When I try to add the .methods to ours it throws an error suggesting .methods is undefined(maybe?)

```
TypeError: Cannot set property 'encrypt' of undefined
    at Object.<anonymous> (/Users/brendanlewis/wdi/exercises/rembr/models/user.js:4:27)
```

**Comment by solowt** [comment]
I had similar issues getting started with passport.

quick thought:

make sure you're adding functions to the schema rather than to the user.  I think it should work if you define encrypt and validate in the schema file like: 

``` js
UserSchema.methods.encrypt = function(password){
...
}
```

it's a bit confusing because the in-class example we did had all of this in one file but I don't see any reason two files wouldn't work, as long as you add methods to the schema.

also, passport does the user saving in config/passport.js so I'd take a look at that for clues as to why users aren't getting saved.  it might be as simple as the encrypt function not working properly though, because encrypt is going to get called inside config/passport.js every time you post a new user.

**Comment by jenpen** [comment]
@solowt : Thanks so much for the pointer Thomas! Set us on the right path.
