### ISSUE TITLE
Feedback on my Rspec suite

### ISSUE THREAD

**Issue by ckib16** [ga-wdi-exercises/project3#26]
# RSpec feedback request

Here's my initial RSpec suite that tests model creation & validations: https://github.com/ckib16/pilot_roster/tree/RSpec_start/spec
FYI: 
- I don't have any class or instance methods to test yet. 
- The suite is passing.
## Questions
- [ ] Is it best practice to re-use Factory Girl with your seeds.rb file? Seems like an easy way to handle it.
- [ ] Did I validate & test booleans correctly? The boolean attribute in question is `:oconus` - see location_spec.rb line 35  & location.rb line 4
  - Here's the S.O. comment I used: http://stackoverflow.com/questions/13371633/testing-for-a-boolean-return-type-in-rspec
- [ ] The book I'm using favors explicitness over DRY to document each individual test. I'm feeling like I should DRY up specs with `:before each` for the validation tests. Thoughts?
- [ ] How to avoid ActiveRecord info from FactoryGirl cluttering up my RSpec info in terminal? (see gist)
  - https://gist.github.com/ckib16/64ec451f398dd693ee34

Next step - controller tests.

**Comment by RobertAKARobin** [comment]
1. [Food for thought](https://robots.thoughtbot.com/factory_girl-for-seed-data)
2. Looks great to me!
3. It's your choice. Personally, I'd go DRY in development since it's much less code to write and I'm likely to be changing variable names and such. Maybe once my app is well-established, with something in production, I'd go to explicit code.
4. Add the following to the end of `config/environments/test.rb`, before the final `end`:

``` rb
  config.after_initialize do
    ActiveRecord::Base.logger = Rails.logger.clone
    ActiveRecord::Base.logger.level = Logger::INFO
  end
```
