### ISSUE TITLE
Mongoose models

### ISSUE THREAD

**Issue by dan-ator** [ga-wdi-exercises/project3#43]
I have the following code in one of my controllers:

``` js
create: function (request, response) {
  User.find(request.params.email, function (err, docs){
    docs.dashboardItems.push(new DashboardItemModel(
      {partner_message: request.body.partner_message},
      {partner_link: request.body.partner_link},
      {city: request.body.city}
    ))
    docs.save(function(err){
      if(!err){
        response.redirect('dashboard.hbs')
      }
    })
  })
},
```

The error I am getting is "TypeError: Cannot read property 'push' of undefined".  I checked in my Mongo repl and the users are created, but I can't get this function to work.

**Comment by dan-ator** [comment]
I think it's relevant, so the User model looks like this:

```
var User = mongoose.Schema({
  local : {
    email        : String,
    password     : String,
  },
  dashboardItem : {
    partner_message: String,
    partner_link: String,
    city: String
  }
});
```

**Comment by RobertAKARobin** [comment]
That means your `docs` has no `dashboardItems`. If `docs` in this case refers to the `User` schema, then `User` should look like this:

``` js
var User = new mongoose.Schema({
    email        : String,
    password     : String,
    dashboardItems : [dashboardItem]
});
```

You're using a bit of a strange format for this which is going to cause errors in the future. I'd recommend rewriting your schema to follow this format:

https://github.com/ga-dc/curriculum/tree/master/08-single-page-web-apps/mongo_mongoose#example-schema

**Comment by dan-ator** [comment]
If I change the User schema away from how we did it in the Passport authent. class, won't that cause issues with all of that?

**Comment by RobertAKARobin** [comment]
Oh, my mistake. I gotcha. In that case, you'll want something like this:

``` js
var User = new mongoose.Schema({
    email        : String,
    password     : String,
    dashboardItems : [{
      partner_message: String,
      partner_link: String,
      city: String
  }]
});
```

Note that I removed the `local`. That is only necessary if you want to have multiple authentication strategies. You have just one, so you don't need to specify it.

The above is what you would use if you only ever want to look at dashboardItems in the context of the Users to which they belong. There is no easy way to query dashboardItems here: say, if you wanted to look for a specific dashboardItem by its city.

To do that, you'd need dashboardItems to have their own table, and then instead of including _entire_ dashboardItems inside a User, you just include the _IDs_ of that user's dashboardItems. This is using Mongo to make a pseudo-relational database.

That would look like this:

``` js
var dashboardItem = new mongoose.Schema({
  partner_message: String,
  partner_link: String,
  city: String
});

var User = new mongoose.Schema({
  email        : String,
  password     : String,
  dashboardItems : [{
    type: mongoose.Schema.Types.ObjectID,
    ref: "DashboardItem"
  }]
});
```
