### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by laburr27** [ga-wdi-exercises/project3#440]
We put both angular and rails in one git repo.  Heroku doesn't like that very much at all.  Below is the error I am getting.  Not sure how to fix this w/o creating a whole new repo in my github profile.

`$ git push heroku master
Counting objects: 295, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (263/263), done.
Writing objects: 100% (295/295), 97.98 KiB | 0 bytes/s, done.
Total 295 (delta 96), reused 109 (delta 11)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote:  !     No default language could be detected for this app.
remote: 			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
remote: 			See https://devcenter.heroku.com/articles/buildpacks
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to bookaroo.
remote: 
To https://git.heroku.com/bookaroo.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/bookaroo.git'`

**Comment by amaseda** [comment]
Based on our discussion earlier, it sounds like you have (roughly) the following folder structure

```
root_directory (git)
  |
  |---  angular-front-end
  |
  |---  rails-back-end
```

I'm guessing you are pushing to heroku from that `root_directory`. The problem is that Heroku needs some sort of buildpack -- which in this scenario let's just say a backend -- in order to successfully deploy your app.

What you need to do is only push your Rails app -- in the above example, `rails-back-end` -- to Heroku and host your Angular app on some static file hosting service like Github Pages.

What you don't want to do is initialize another git repository inside of `root_directory` since that directory itself is already a git repository. So two options are...
  1.  Create two new repos, one for your front-end and one for your back-end. Then push the latter to heroku. Only issue here is that your commit history might disappear, which is not ideal, especially given that we need it for project evaluation.
  2. Copy your Rails app to another local directory. Initialize that directory as a git repo using `git init` and then create/push to Heroku from there.

Happy to elaborate. Let me know if you have any questions/comments.

**Comment by superbuggy** [comment]
just push your back-end to heroku. make a separate branch for deploying to Heroku, and have just your rails app in it. make sure you are very careful about managing changes within and across branches, and being aware of what branch you are on when making changes

**Comment by laburr27** [comment]
NVMD - Figured it out myself with a little hint about an asterisk!
------
Got it...Branch made and irrelevant files deleted.  How do I move the contents of the folder into the root directory now?

**Comment by laburr27** [comment]
Ok...this is what I did:
1) Created branch rails-back-end
1a) Verified am in that branch
2) Deleted irrelevant files and moved rails content to root
3) Deleted "bad" app on heroku
4) Did bundle install
5) Did bundle update
6) Did $ rails db:drop db:create db:migrate db:seed
7) Did $ heroku create bookaroo
MESSAGE: Creating ⬢ bookaroo... done
https://bookaroo.herokuapp.com/ | https://git.heroku.com/bookaroo.git
8) Did $ git push heroku master
SAME ERROR AS BEFORE
9) Did $ git push heroku rails-back-end
MESSAGE: 
Counting objects: 313, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (281/281), done.
Writing objects: 100% (313/313), 101.49 KiB | 0 bytes/s, done.
Total 313 (delta 105), reused 109 (delta 11)
remote: Pushed to non-master branch, skipping build.
To https://git.heroku.com/bookaroo.git
 * [new branch]      rails-back-end -> rails-back-end

Still no success on deployment...

**Comment by amaseda** [comment]
Which directory (not branch) are you deploying from? What are the contents if it? Not sure what they look like since you commented earlier!

**Comment by laburr27** [comment]
Wed Mar 15 15:33:12 ~/wdi/projects/project3 (rails-back-end)

**Comment by amaseda** [comment]
What are contents of `project3`? Is your Rails app located at the top level of that directory?

**Comment by laburr27** [comment]
![screen shot 2017-03-15 at 5 11 58 pm](https://cloud.githubusercontent.com/assets/25046132/23971031/9ad033f4-09a2-11e7-8e48-e75087508d72.png)

**Comment by amaseda** [comment]
Ah, can you do this...

`git push heroku your-branch-name:master`

> Make sure to replace `your-branch-name` with the correct one

**Comment by laburr27** [comment]
YES!  SUCCESS!!!! (said very cautiously)...

**Comment by amaseda** [comment]
:+1:

The issue was that Heroku expects you to push code to its master branch. So by saying `your-branch-name:master`, you're pushing the contents of your local branch to heroku's master branch.

@laburr27
