### ISSUE TITLE
Links stopped working, no idea what's wrong

### ISSUE THREAD

**Issue by fanelenan7** [ga-wdi-exercises/project3#443]
After tampering with RouterFunction (to get animations working), the 2 ot of 3 buttons stopped responding. I'm not sure what happened.
```
function RouterFunction($stateProvider) {
  $stateProvider
    .state("bookarooIndex", {
      url: "/",
      templateUrl: "js/ng-views/index.html",
      controller: "bookarooIndexController",
      controllerAs: "vm",
      // clear animation and bookmarks
      onEnter: function() {
        document.querySelectorAll(".bookmark").forEach((bookmark) => {
          bookmark.style.display = "none"
        })
      }
    })
    .state("bookaroo", {
      url: "/books/:id",
      templateUrl: "js/ng-views/show.html",
      controller: "bookarooShowController",
      controllerAs: "vm",
      // animation trigger on enter
      onEnter: function() {
        document.querySelectorAll(".bookmark").forEach((bookmark) => {
          bookmark.style.display = "flex"
          let newElement = bookmark.cloneNode(true)
          bookmark.parentNode.replaceChild(newElement, bookmark)
        })
      }
    
    })
}
```
here are the bookmarks
```
      <a class ="bookmark" data-ng-click="vm.book.showInformation = !vm.book.showInformation">Information</a>
      <a class ="bookmark" data-ng-click="reloadRoute()">Find a New Book</a>
      <a class ="bookmark" id="collapse" data-ui-sref="bookarooIndex">Start Over</a>
```
3rd one is the only one that works. I'm not sure what is wrong, it all worked before.

**Comment by superbuggy** [comment]
Can you describe what kind of changes you made to your router function?

**Comment by fanelenan7** [comment]
Both "onEnter" functions were added.

**Comment by superbuggy** [comment]
Is the controller still operating in the template? Sounds like the template-binding might've been broken? 

is `reloadRoute()` a function you've defined or is that in uirouter?

**Comment by fanelenan7** [comment]
reloadRoute is defined in the show controller.
```
  $scope.reloadRoute = function() {
    $state.reload();
  }
```

Ummmm... How to I check if controller is separated or not?

**Comment by superbuggy** [comment]
`console.log(this)` as the first line of the controller function

**Comment by fanelenan7** [comment]
bookarooShowControllerFunction {} pops up when I hit the button to go to the show view.
Seems to be fine.

**Comment by superbuggy** [comment]
can you add a `console.log` to reloadRoute and verify that function doesn't run?

**Comment by superbuggy** [comment]
if it still doesn't, can you just attach the function defintion to the viewmodel instead of $scope?

**Comment by fanelenan7** [comment]
Hm, I think Justin got both of the buttons working. Don't know how yet, going to let you know. Thanks, James.

**Comment by superbuggy** [comment]
ok, cool! closing for now.

**Comment by Justin-Shin** [comment]
@superbuggy @fanelenan7 
The two buttons stopped working because they were originally defined in the scope of the show model, and they were written into that file.  For styling, they were moved out of show.html into the parent index.html page.  This pulled the ng-data-hide/reloadRoute() out of the scope of the show controller, which caused them to cease functioning.  The router changes didn't affect it, we just didn't notice until later.

I added jquery to the show controller so that whenever show.html loads, the jquery listeners get remade.  These listen to the index.html buttons and do changes within the controller.  I had to get rid of angular handling (data-ng-hide) for the toggle between information and preview, and handled it via jquery/css.
