### ISSUE TITLE
Refreshing Page Causes the Page to Not Show Content

### ISSUE THREAD

**Issue by hawkins-will** [ga-wdi-exercises/project3#446]
When you refresh a page in our app, it stops showing content and you have to navigate back to the Home page. We don't know why this is happening.

Any ideas?

**Comment by amaseda** [comment]
By "content" do you mean everything on the page or particular content (e.g., only things on the layout remain, information pulled from the database disappears).

**Comment by hawkins-will** [comment]
The only thing that remains is the header. Everything else contained in any of the viewfiles poofs away

**Comment by amaseda** [comment]
I think you're losing your last state when refreshing. You can use `.otherwise` to redirect the user to a particular route (say index) when the page is refreshed (or any other situations where the user is directed to an incorrect or nonexistent route.

https://github.com/angular-ui/ui-router/wiki/URL-Routing#otherwise-for-invalid-routes

**Comment by nayana487** [comment]
gonna close since I think we're set on this, re-open if needed
