### ISSUE TITLE
GET (some url) 404 not found

### ISSUE THREAD

**Issue by edawson1980** [ga-wdi-exercises/project3#476]
We are still trying to get our MVP up and running, and I feel like we've managed to whittle down the errors.  However, I've started getting this error in the console:
<img width="1152" alt="screen shot 2017-05-15 at 3 29 08 pm" src="https://cloud.githubusercontent.com/assets/16961196/26075432/474454a2-3983-11e7-81b4-46be301f181a.png">

but - 
my path in my VotesFunction is 
`
function VotesFunction($resource) {
    return $resource("http://localhost:3000/stations/:station_id/votes/")
  }
`

so my question is, why would the browser read the path as not having ':station_id' in it?

i've created a Votes Factory, and made the updates to our StationShowControllerFunction:
`  function StationShowControllerFunction(WeatroFactory, VotesFactory, $stateParams) {
    this.station = WeatroFactory.get({id: $stateParams.id});
    this.votes = VotesFactory.get({station_id: $stateParams.station_id});
  }`

additionally, i followed a thread and ended up creating a new module called VotesModule (set to the variable VotesModule), and then made it dependent on 'weatro' (our original module).  i don't know if that was a smart or even necessary move - but it definitely got rid of most of the errors I had been having.

**Comment by jsm13** [comment]
The screen shot suggests that `$stateParams.station_id` is undefined since the request is going to a URL without a `station_id`. What do you get if you `console.log($stateParams.station_id)` before making that request?

**Comment by edawson1980** [comment]
that makes sense, as our votes are nested inside of our stations.  the browser would only be pointing at station with id('whatever').
i just rewrote it to $stateParams.id

this gives me a different error (which is a sign of progress, if i'm to believe what i'm told haha):
it's still a 404 but now the url reads:
http://localhost:3000/stations/votes?id=1

we have a vote with the id of 1.
could this be because i've created a new module?  if so, i created the new module as a result of following an error message that suggested "Instead create your own module and add it as a dependency to your application's top-level module. See #9692 and #7709 for more information"
and i got that error when i had set
    this.votes = VotesFactory.get({id: $stateParams.id});

i feel like we're in a never-ending loop.

**Comment by jsm13** [comment]
I wouldn't expect you to need a new module. Looking at the url `http://localhost:3000/stations/votes?id=1` it looks like that was produced from a resource that had been defined with a url string that didn't have `:id` which is why it is being added as a query string (after the `?`). I think you want `this.votes = VotesFactory.get({station_id: $stateParams.id});`

**Comment by edawson1980** [comment]
right on.  we're back to getting an error i was getting before, but now i think we can figure out a way to fix it.
the error is that $resource is expecting an object, but is getting an array...i think this is because our Vote model is an array?

**Comment by jsm13** [comment]
That would do it. If the response is an array, the action needs to be defined with `isArray: true` (of the default in actions, only `query` expects the response to be an array. You will want to either a) define a custom action for the resource ([described in the $resource docs here, sorry I can't link directly to the paragraph](https://docs.angularjs.org/api/ngResource/service/$resource)) b) use query instead of get (only if appropriate) or c) update the rails controller to respond with an object rather than an array

**Comment by edawson1980** [comment]
awesome!  thank you!
