### ISSUE TITLE
ng-resource issue

### ISSUE THREAD

**Issue by tedlayea** [ga-wdi-exercises/project3#499]
We are done with Rails API and its working. But when we use ng-resource to use it in angular part, we are getting an empty array.
![ng-resouce_issue](https://user-images.githubusercontent.com/27984226/27647237-e5ae5812-5bf8-11e7-8906-43fcc8f32452.png)
Thanks

**Comment by amaseda** [comment]
Is the API definitely returning JSON (i.e., are you indicating anywhere in your front-end or back-end that you need the response in JSON form, not HTML)?

**Comment by superbuggy** [comment]
the `$resource.badcfg` occurs when the factory method `.query()` 'receives' a response that is object instead of an array, or when the `.get()` 'receives' a response that is an array instead of an object.

Where you have placed your `console.log` in your code will affect what is logged, due to the asynchronous nature of the XHR request that `$resource` is making.

**Comment by tedlayea** [comment]
Yes, API is returning JSON  and also HTML in Rails side. But nothing in angular side.

**Comment by amaseda** [comment]
What happens if you add `.json` to the end of the `$resource` URL?

**Comment by tedlayea** [comment]
Ya, thanks that solved the problem.

**Comment by amaseda** [comment]
:+1:
