### ISSUE TITLE
problem with user authentication

### ISSUE THREAD

**Issue by rebeccaestes** [ga-wdi-exercises/project3#52]
I've set up user authentication with Passport and the sign up screen displays, but whenever you click the Submit button I get the error: `TypeError: next is not a function`. 

It appears to be breaking on the line `return signupStrategy(req, res);` signupStrategy is defined earlier in the function and calls `passport.authenticate`, so I guess it's something happening there. I've tried to match all the code to what we did in the local authentication exercise last week and none of that helped.

**Comment by ghost** [comment]
We had this same issue yesterday and we were missing a require I'm going to try and look for where it was

**Comment by ghost** [comment]
we had to add this to our users controller 

```
require('../config/passport')(passport) 
```

our passport file is in a config folder

**Comment by rebeccaestes** [comment]
I swear I tried that (several times ...), but somehow it looks to be working now! Thanks.

**Comment by amaseda** [comment]
Don't know why but Passport is one of those things that magically starts working sometimes. Frustrating!

**Comment by ZebGirouard** [comment]
I don't think I have the ability to re-open this, but I think I figured out what is going on here, and I found this by Googling so others may, too.  The code we have in our express-passport lesson has only (request, response) as parameters in our controllers.  This does not affect most users, and I'm pretty sure @rebeccaestes is in a similar position, precisely because they do *not* have errors.  Looking at the stack trace for any of these issues, they revolve around the `authenticate.js` file inside the `passport` node_modules folder.  If you look at the actual lines of code (I have seen three separate lines referenced with the same "next is not defined" TypeError line), they are trying to throw an error with the next() function.  The only problem is `next` is not defined (we didn't pass it when we invoked the login/signup strategy), so it can't even throw the real error (it doesn't get that far).  For example, line 194 in node_modules/passport/lib/passport/middleware/authenticate.js may give a "next is not defined" because here:

        req.logIn(user, options, function(err) {
          if (err) { return next(err); }

There was an error when trying to login...but we can't see it because `next` is not defined.  The solution is to turn something like this:

```
function postLogin(request, response) {
	var loginStrategy = passport.authenticate('local-login', {
		successRedirect: '/',
		failureRedirect: '/login',
		failureFlash : true
	});

	return loginStrategy(request, response);	
}
```

into this:

```
function postLogin(request, response, next) {
	var loginStrategy = passport.authenticate('local-login', {
		successRedirect: '/',
		failureRedirect: '/login',
		failureFlash : true
	});

	return loginStrategy(request, response, next);	
}
```

Now, instead of "next is not defined", we will see something about the req.logIn failure (req is not defined, etc.), and we will actually be troubleshooting the, dare I say, _correct_ issue.

I'm also creating a pull request to the express-passport lesson in ga-wdi to add next to these controllers so this doesn't burn people in the future.  This was really hard to find.
