### ISSUE TITLE
information load time

### ISSUE THREAD

**Issue by preese13** [ga-wdi-exercises/project3#533]
when loading a state with information from an API, it quickly flashes in API format before transforming into the proper format.  How can I erase this eyesore from my page?

https://github.com/jessamarie/Moments

**Comment by jsm13** [comment]
Not sure specifically where you're seeing this but what you'll want to do is instead of directly assigning the resource to a property of the `vm` you'll want to explicitly handle the promise as is being done in [`loadMoments`](https://github.com/jessamarie/Moments/blob/master/src/moments/show.controller.js#L32-L77) (load moments does more than just handle the formatting of the data but in your described scenario that's all you'd need to do)

**Comment by perryf** [comment]
ok, we will give that a shot, thanks!
